services:
  whisperAPI:
    image: ghcr.io/mayniklas/whisper_api:latest
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LOAD_MODEL_ON_STARTUP=1
      # - UNLOAD_MODEL_AFTER_S=300
      # - DEVELOP_MODE=0
    # include the following lines when using a NVIDIA GPU!
    # make sure to have the NVIDIA Container Toolkit installed
    # for more information visit:
    # https://github.com/NVIDIA/nvidia-container-toolkit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
