version: "3.9"
services:
  api:
    image: "mayniklas/whisper_api:latest"
    build:
      context: .
      # use Dockerfile.gpu when using a NVIDIA GPU
      dockerfile: Dockerfile.gpu
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - LOAD_MODEL_ON_STARTUP=1
      # - UNLOAD_MODEL_AFTER_S=300
      # - DEVELOP_MODE=0
    # Uncomment the following lines when using a NVIDIA GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
