labels:
  backend: local
  platform: "linux/amd64"

steps:
  - name: setup attic
    image: bash
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default
    secrets: [attic_key]

  - name: build whisper_api
    image: bash
    commands:
      - nix build --print-out-paths .#whisper_api

  - name: push whisper_api
    image: bash
    commands:
      - attic push nix-cache result

  - name: build whisper_api_withoutCUDA
    image: bash
    commands:
      - nix build --print-out-paths .#whisper_api_withoutCUDA

  - name: push whisper_api_withoutCUDA
    image: bash
    commands:
      - attic push nix-cache result

  - name: build whisper_api_withCUDA
    image: bash
    commands:
      - nix build --print-out-paths .#whisper_api_withCUDA

  - name: push whisper_api_withCUDA
    image: bash
    commands:
      - attic push nix-cache result

  - name: build devShell without CUDA
    image: bash
    commands:
      - nix build --print-out-paths .#devShells.x86_64-linux.withoutCUDA

  - name: push devShell without CUDA
    image: bash
    commands:
      - attic push nix-cache result

  - name: build devShell with CUDA
    image: bash
    commands:
      - nix build --print-out-paths .#devShells.x86_64-linux.withCUDA

  - name: push devShell with CUDA
    image: bash
    commands:
      - attic push nix-cache result
